import type { Metadata } from "next";
import "./globals.css";
import { NextAuthProvider } from "@/components/universal/Providers";
import SidebarProviderContainer from "@/components/navbar/SidebarProviderContainer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="h-screen overflow-hidden">
        <NextAuthProvider>
          <div className="flex h-screen">
            <div className="">
              <SidebarProviderContainer />
            </div>
            <main className="flex-1 h-[calc(100vh-64px)]">{children}</main>
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
